# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeHaveNoJob-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Core'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare' 
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
  # Pods for WeHaveNoJob-iOS


end
